[project]
name = "laboratory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "notebook>=7.5.0",
    "onnxruntime>=1.23.2",
    "onnxscript>=0.5.6",
    "torch>=2.9.1",
    "transformers>=4.57.1",
]
