# common configuration with anchor
x-airflow-common: &airflow-common
  build:
    context: .
    args:
      AIRFLOW_IMAGE_NAME: apache/airflow:3.1.5-python3.11
  env_file:
    - .env
  environment:
    # DB and Celery executor
    &airflow-common-env
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CELERY__BROKER_URL: redis://:@valkey:6379/0
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow

    # Airflow Variables and Connections
    AIRFLOW_VAR_TWELVEDATA_API_KEY: "${TWELVEDATA_API_KEY}"


    # a few general settings
    AIRFLOW_CONFIG: '/opt/airflow/config/airflow.cfg'
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: "http://airflow-apiserver:8080/execution/"
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: "true"
    AIRFLOW__DAG_PROCESSOR__REFRESH_INTERVAL: "10"

    # fake security for local setup, load this from .env or remote secret backend in production!
    AIRFLOW__CORE__FERNET_KEY: "-hOWXdt95LqMn8jDdoqplHgSlzEuqUPnCHLwnsMQcZU="
    AIRFLOW__API__SECRET_KEY: "sv3N1i8Wwu9W6IsUvcDjCg=="
    AIRFLOW__API_AUTH__JWT_SECRET: "sv3N1i8Wwu9W6IsUvcDjCg=="

    # use uv + cache
    AIRFLOW__STANDARD__VENV_INSTALL_METHOD: "uv"
    UV_CACHE_DIR: /opt/airflow/.uv-cache

    # set up LocalStack S3 as XCom backend
    AIRFLOW__CORE__XCOM_BACKEND: "airflow.providers.common.io.xcom.backend.XComObjectStorageBackend"
    AIRFLOW__COMMON_IO__XCOM_OBJECTSTORAGE_PATH: "s3://aws_default@airflow-xcom/xcom"
    AIRFLOW__COMMON_IO__XCOM_OBJECTSTORAGE_THRESHOLD: "0" # threshold 0 = all files are stored in S3
    # URL-encoded fake AWS connection, we must set endpoint_url for LocalStack
    AIRFLOW_CONN_AWS_DEFAULT: 'aws://test:test@localstack?endpoint_url=http%3A%2F%2Flocalstack%3A4566&region_name=us-east-1'

  volumes:
    # volumes to sync local environment and containers
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./config:/opt/airflow/config
    - uv-cache:/opt/airflow/.uv-cache

  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    postgres:
      condition: service_healthy
    valkey:
      condition: service_healthy
    postgres-storage:
      condition: service_healthy
    localstack:
      condition: service_healthy

services:
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      SERVICES: "s3" # just S3 service
    volumes:
      - localstack_data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./localstack-init:/etc/localstack/init
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:4566/_localstack/health" ]
      interval: 10s
      retries: 10
    restart: always

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 10s
      retries: 5
    restart: always

  valkey:
    image: valkey/valkey:9
    healthcheck:
      test: [ "CMD", "valkey-cli", "ping" ]
    restart: always

  postgres-storage:
    image: postgres:17
    environment:
      POSTGRES_USER: storage_user
      POSTGRES_PASSWORD: storage_pass
      POSTGRES_DB: storage_db
    volumes:
      - postgres-storage-volume:/var/lib/postgresql/data
      - ./postgres-storage-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "storage_user", "-d", "storage_db" ]
      interval: 10s
      retries: 5
    restart: always

  airflow-init:
    <<: *airflow-common
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow
      _PIP_ADDITIONAL_REQUIREMENTS: ''
    user: "0:0"

  airflow-apiserver:
    <<: *airflow-common
    command: api-server
    ports:
      - "8080:8080"
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    restart: always

  airflow-worker:
    <<: *airflow-common
    command: celery worker
    environment:
      <<: *airflow-common-env
      DUMB_INIT_SETSID: "0"
      AIRFLOW__CELERY__WORKER_CONCURRENCY: "4"
    depends_on:
      airflow-apiserver:
        condition: service_started
      airflow-init:
        condition: service_completed_successfully
    restart: always

  airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    restart: always

  airflow-dag-processor:
    <<: *airflow-common
    command: dag-processor
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    restart: always

volumes:
  postgres-db-volume:
  postgres-storage-volume:
  uv-cache:
  localstack_data:
